import { Bundle, Tool, Testimonial, FAQ } from '@/types';

export const BUNDLES: Bundle[] = [
  {
    id: 'essential',
    name: 'Essential Tools',
    price: 19.99,
    priceInPence: 1999,
    description: 'Start your project on solid foundations',
    features: [
      { name: 'Extension Decision Calculator', format: 'XLSX', description: 'Compare extending vs. moving with cost breakdown' },
      { name: 'Budget Planner', format: 'XLSX', description: 'Track all costs with 20% contingency built in' },
      { name: 'PD Flowchart', format: 'DOCX', description: 'Do you need planning permission? Find out.' },
    ],
  },
  {
    id: 'complete',
    name: 'Complete Toolkit',
    price: 39.99,
    priceInPence: 3999,
    description: 'Everything you need from start to finish',
    popular: true,
    features: [
      { name: 'Everything in Essential', included: true },
      { name: 'Project Brief Template', format: 'DOCX', description: 'Lock down scope before spending' },
      { name: 'Builder Scorecard', format: 'XLSX', description: 'Compare builders objectively' },
      { name: 'Payment Schedule', format: 'XLSX', description: 'Never get ahead on payments' },
      { name: 'Planning Tracker', format: 'XLSX', description: 'Track applications and deadlines' },
    ],
  },
  {
    id: 'professional',
    name: 'Professional Plus',
    price: 59.99,
    priceInPence: 5999,
    description: 'All 10 tools plus one free update included',
    features: [
      { name: 'Everything in Complete Toolkit', included: true },
      { name: 'Communication Log', format: 'XLSX', description: 'Document everything for disputes' },
      { name: 'Document Checklist', format: 'DOCX', description: 'Never miss a certificate' },
      { name: 'Snagging Checklist', format: 'XLSX', description: 'Professional defect tracking' },
      { name: 'Variation Register', format: 'XLSX', description: 'Control scope creep' },
      { name: '1 Free Update Included', badge: 'BONUS', description: 'Updated tools with latest rates and regulations' },
    ],
  },
];

export const TOOLS: Tool[] = [
  {
    id: 'calculator',
    name: 'Extension Decision Calculator',
    format: 'XLSX',
    description: 'Should you extend or move? This calculator compares the true costs of both options.',
    features: [
      'Postcode-based regional cost adjustments',
      'Automatic stamp duty calculation',
      'Value uplift sensitivity slider',
      'Side-by-side comparison view',
      'Professional fees included',
    ],
    bundle: ['essential', 'complete', 'professional'],
    generator: 'calculator',
    filename: 'Extension-Decision-Calculator.xlsx',
  },
  {
    id: 'budget',
    name: 'Budget Planner',
    format: 'XLSX',
    description: 'Track all costs with category breakdown and contingency alerts.',
    features: [
      'Dashboard with visual progress',
      'Category breakdown (Professional, Planning, Construction, etc.)',
      'Automatic contingency tracking',
      'Variance alerts when over budget',
      'Receipt tracking',
    ],
    bundle: ['essential', 'complete', 'professional'],
    generator: 'budget',
    filename: 'Budget-Planner.xlsx',
  },
  {
    id: 'pd-flowchart',
    name: 'Permitted Development Flowchart',
    format: 'DOCX',
    description: 'Decision tree for planning requirements.',
    features: [
      'Step-by-step assessment',
      'Covers all extension types',
      'Conservation area rules',
      'Prior approval guidance',
      'Clear yes/no outcomes',
    ],
    bundle: ['essential', 'complete', 'professional'],
    generator: 'pd-flowchart',
    filename: 'Permitted-Development-Flowchart.docx',
  },
  {
    id: 'scope',
    name: 'Project Brief & Scope Template',
    format: 'DOCX',
    description: 'Define requirements with specification sheets.',
    features: [
      'Room-by-room requirements',
      'Must have vs. nice to have lists',
      'Specification standards',
      'Scope lock agreement',
      'Variation control process',
    ],
    bundle: ['complete', 'professional'],
    generator: 'scope',
    filename: 'Project-Brief-Scope-Template.docx',
  },
  {
    id: 'builder-scorecard',
    name: 'Builder Vetting Scorecard',
    format: 'XLSX',
    description: 'Compare up to 10 builders with weighted scoring.',
    features: [
      'Compare up to 10 builders',
      'Weighted scoring system',
      'Insurance verification checklist',
      'Reference tracking',
      'Automatic ranking',
    ],
    bundle: ['complete', 'professional'],
    generator: 'builder-scorecard',
    filename: 'Builder-Vetting-Scorecard.xlsx',
  },
  {
    id: 'payment-schedule',
    name: 'Payment Schedule Template',
    format: 'XLSX',
    description: 'Milestone-based payment tracking with warnings.',
    features: [
      'Milestone-based payments',
      'Retention tracking',
      'Payment vs. completion alerts',
      'Receipt logging',
      'Defects period tracking',
    ],
    bundle: ['complete', 'professional'],
    generator: 'payment-schedule',
    filename: 'Payment-Schedule-Template.xlsx',
  },
  {
    id: 'planning-tracker',
    name: 'Planning Application Tracker',
    format: 'XLSX',
    description: 'Track applications, deadlines, officer contact.',
    features: [
      'Application timeline tracking',
      'Document checklist',
      'Officer contact log',
      'Deadline reminders',
      'Decision tracking',
    ],
    bundle: ['complete', 'professional'],
    generator: 'planning-tracker',
    filename: 'Planning-Application-Tracker.xlsx',
  },
  {
    id: 'communication-log',
    name: 'Communication Log',
    format: 'XLSX',
    description: 'Track all project communications with follow-ups.',
    features: [
      'Email/call/meeting logging',
      'Follow-up reminders',
      'Dispute evidence trail',
      'Attachment references',
      'Search and filter',
    ],
    bundle: ['professional'],
    generator: 'communication-log',
    filename: 'Communication-Log.xlsx',
  },
  {
    id: 'document-checklist',
    name: 'Document Checklist',
    format: 'DOCX',
    description: 'Certificate tracking and sale-ready pack list.',
    features: [
      'All required certificates',
      'Warranty tracking',
      'Sale-ready pack checklist',
      'Missing document actions',
      'Expiry date tracking',
    ],
    bundle: ['professional'],
    generator: 'document-checklist',
    filename: 'Document-Checklist.docx',
  },
  {
    id: 'snagging',
    name: 'Snagging Checklist',
    format: 'XLSX',
    description: 'Room-by-room defect tracking with photo log.',
    features: [
      'Room-by-room sheets',
      'Severity classification',
      'Photo reference logging',
      'Resolution tracking',
      'Final payment gate',
    ],
    bundle: ['professional'],
    generator: 'snagging',
    filename: 'Snagging-Checklist.xlsx',
  },
  {
    id: 'variation-register',
    name: 'Variation Request Register',
    format: 'XLSX',
    description: 'Track scope changes with cost impact.',
    features: [
      'Change request logging',
      'Cost impact tracking',
      'Approval workflow',
      'Timeline impact',
      'Running total',
    ],
    bundle: ['professional'],
    generator: 'variation-register',
    filename: 'Variation-Request-Register.xlsx',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: "The budget planner saved us. We caught a £12,000 discrepancy before paying. Worth every penny.",
    author: "Sarah M.",
    location: "Bristol",
    rating: 5,
    project: "Kitchen extension",
  },
  {
    quote: "I compared 5 builders using the scorecard. The one I nearly chose based on price alone scored lowest on references. Dodged a bullet.",
    author: "James T.",
    location: "Manchester",
    rating: 5,
    project: "Two-storey extension",
  },
  {
    quote: "The snagging checklist found 47 defects the builder said were 'normal'. Got them all fixed before final payment.",
    author: "Emma R.",
    location: "Surrey",
    rating: 5,
    project: "Loft conversion",
  },
];

export const FAQS: FAQ[] = [
  {
    question: "What software do I need to use these tools?",
    answer: "The XLSX files work with Microsoft Excel 2016 or later, Google Sheets, LibreOffice Calc, and Apple Numbers. The DOCX files work with Microsoft Word 2016 or later, Google Docs, and LibreOffice Writer. All formulas and formatting are fully compatible.",
  },
  {
    question: "What if the tools don't work for me?",
    answer: "We offer a 30-day money-back guarantee, no questions asked. If you're not satisfied for any reason, email us and we'll refund your purchase in full.",
  },
  {
    question: "How do updates work for Professional Plus?",
    answer: "Professional Plus includes one free update with the latest building regulations, planning rules, and cost benchmarks. When an update is available, it will be emailed to you automatically.",
  },
  {
    question: "How do I receive the files?",
    answer: "After payment, you'll immediately see a download page with links to all your files. You'll also receive an email with the same download links. Downloads are available for 30 days, and you can request new links anytime.",
  },
  {
    question: "Can I share these with my partner/spouse?",
    answer: "Yes! The tools are licensed for personal use on one project. You can share them with anyone in your household working on the same extension project. Please don't share publicly or resell.",
  },
  {
    question: "Do these work for Scotland/Wales/Northern Ireland?",
    answer: "The financial tools (budget planner, calculator, payment schedule) work throughout the UK. The planning tools are designed for England and Wales permitted development rules. Scotland and Northern Ireland have different planning systems - the principles apply but check local regulations.",
  },
];

export function getToolsForBundle(bundleId: string): Tool[] {
  return TOOLS.filter(tool => tool.bundle.includes(bundleId as any));
}
